# Generated by Django 5.0 on 2024-02-15 12:09

import account.manager
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ticket', '0002_events_ticket_transaction_delete_razorpaypayments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('Splash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Splash_Event', to='ticket.events')),
                ('technical1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technical_Event_1', to='ticket.events')),
                ('technical2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technical_Event_2', to='ticket.events')),
            ],
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
