# Generated by Django 5.0 on 2024-02-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_pass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.passes'),
        ),
        migrations.AlterField(
            model_name='passes',
            name='Splash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Splash_Event', to='ticket.events'),
        ),
        migrations.AlterField(
            model_name='passes',
            name='technical1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Technical_Event_1', to='ticket.events'),
        ),
        migrations.AlterField(
            model_name='passes',
            name='technical2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Technical_Event_2', to='ticket.events'),
        ),
    ]
