# Generated by Django 4.2.7 on 2023-12-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
