# Generated by Django 4.2.7 on 2023-12-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username_alter_user_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
