# Generated by Django 5.0 on 2024-02-25 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otp_created_alter_otp_expire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTP(s)'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sem',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 38, 18, 138600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 38, 48, 138626, tzinfo=datetime.timezone.utc)),
        ),
    ]
