# Generated by Django 5.0 on 2024-02-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_passes_splash_alter_passes_technical1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passes',
            old_name='Splash',
            new_name='splash',
        ),
    ]
