# Generated by Django 5.0 on 2024-02-17 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 11, 46, 38, 544676)),
        ),
    ]
