# Generated by Django 5.0 on 2024-02-17 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 11, 48, 35, 57619)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
