# Generated by Django 4.2.7 on 2024-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
