# Generated by Django 5.0 on 2023-12-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayments',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='credit', max_length=6),
            preserve_default=False,
        ),
    ]
