# Generated by Django 5.0 on 2024-01-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_event_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='money',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('splash', 'Splash'), ('tech', 'Technical')], max_length=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.event'),
        ),
    ]
