# Generated by Django 5.0 on 2024-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_customticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
