# Generated by Django 5.0 on 2024-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_events_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(default='', upload_to='media/events/'),
            preserve_default=False,
        ),
    ]
