# Generated by Django 5.0 on 2024-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_events_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
