# Generated by Django 4.2.7 on 2024-02-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_rename_cost_events_amount_alter_events_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
