# Generated by Django 5.0 on 2024-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_rename_cost_events_amount_alter_events_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(default='C Block', max_length=100),
            preserve_default=False,
        ),
    ]
