# Generated by Django 5.0 on 2024-02-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_delete_transaction'),
        ('ticket', '0010_events_venue'),
    ]

    operations = [
    ]
